#!/usr/bin/env python
# NOTE: Example code is generated by Claude Opus 4.8
#
# Drive the 3-D beam-driven plasma wakefield (PWFA) simulation defined in
# plasma_acceleration.yaml and make a few diagnostic plots.
#
#   python run.py
#
# Diagnostics are written under <path>/diags; we set path=./output.

import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from warpx import WarpX

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "output")

w = WarpX(input_file=os.path.join(HERE, "plasma_acceleration.yaml"), path=OUTDIR, verbose=True)
w.run()  # configures, steps the simulation, and auto-loads every diagnostic series

# --- Wakefield (fields) --------------------------------------------------------
# Longitudinal accelerating field Ez in the x-z plane (slice through y=0). The
# drive beam carves out a wake whose Ez alternates sign behind the bunch.
fig = w.plot_fields("Ez", "x", "z")
fig.savefig(os.path.join(HERE, "wakefield_Ez_xz.png"), dpi=140, bbox_inches="tight")

# --- Beam diagnostics (particles) ----------------------------------------------
# Drive-beam longitudinal phase space: z vs. pz. The dense relativistic bunch
# sits at the head of the box and drives the wake.
fig = w.plot2D("z", "pz", species="beam")
fig.savefig(os.path.join(HERE, "phase_space_beam_z_pz.png"), dpi=140, bbox_inches="tight")

# Longitudinal current density Jz in the x-z plane: the drive beam shows up as
# a compact current channel, the source term that drives the wake. (After only
# 10 steps the cold background plasma has barely responded, so its phase space
# is uninformative; the beam current is the more illustrative companion to Ez.)
fig = w.plot_fields("Jz", "x", "z")
fig.savefig(os.path.join(HERE, "current_Jz_xz.png"), dpi=140, bbox_inches="tight")

plt.close("all")
print("\nDone. Wrote wakefield_Ez_xz.png, phase_space_beam_z_pz.png, "
      "current_Jz_xz.png to")
print(f"  {HERE}")
