#!/usr/bin/env python
# NOTE: Example code is generated by Claude Opus 4.8
#
# Drive the uniform-plasma benchmark defined in uniform_plasma.yaml and make a
# few diagnostic plots.
#
#   python run.py
#
# Diagnostics are written under <path>/diags; we set path=./output.

import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from warpx import WarpX

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "output")

w = WarpX(input_file=os.path.join(HERE, "uniform_plasma.yaml"), path=OUTDIR, verbose=True)
w.run()  # configures, steps the simulation, and auto-loads every diagnostic series

# --- Field diagnostics ---------------------------------------------------------
# Charge-density fluctuations across the box. A uniform plasma stays globally
# neutral, so rho is dominated by small thermal/numerical fluctuations rather
# than any large-scale structure. (x, z are the physical in-plane 2D axes.)
fig = w.plot_fields("rho", "x", "z")
fig.savefig(os.path.join(HERE, "rho_xz.png"), dpi=140, bbox_inches="tight")

# --- Beam diagnostics (particles) ----------------------------------------------
# Longitudinal phase space: z vs. pz. The thermal electrons fill the box with a
# Gaussian pz spread and no net drift.
fig = w.plot2D("z", "pz")
fig.savefig(os.path.join(HERE, "phase_space_z_pz.png"), dpi=140, bbox_inches="tight")

# Per-slice transverse extent vs. z. The electrons uniformly fill the box, so
# the transverse RMS size (sigma_x) of each z-slice should be essentially flat
# across the domain -- a simple check that the plasma stays spatially uniform.
fig = w.plot1D("z", "sigma_x")
fig.savefig(os.path.join(HERE, "sigma_x_vs_z.png"), dpi=140, bbox_inches="tight")

plt.close("all")
print("\nDone. Wrote rho_xz.png, phase_space_z_pz.png, sigma_x_vs_z.png to")
print(f"  {HERE}")
