#!/usr/bin/env python
# NOTE: Example code is generated by Claude Opus 4.8
#
# Drive the 150 keV thermionic-gun simulation defined in gun.yaml and make a
# couple of diagnostic plots.
#
#   python run.py
#
# Diagnostics are written under <path>/diags; we set path=./output.

import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from warpx import WarpX

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "output")

w = WarpX(input_file=os.path.join(HERE, "gun.yaml"), path=OUTDIR, verbose=True)
w.run()  # configures, steps the simulation, and auto-loads every diagnostic series

# --- Beam diagnostics (particles) ----------------------------------------------
# Longitudinal phase space: z vs. kinetic energy. The beam should stream toward
# the anode and approach 150 keV.
fig = w.plot2D("z", "kinetic_energy")
fig.savefig(os.path.join(HERE, "phase_space_z_KE.png"), dpi=140, bbox_inches="tight")

# Beam centroid position vs. time: the emitted bunch marches across the gap.
fig = w.plot1D("t", "mean_z")
fig.savefig(os.path.join(HERE, "centroid_z_vs_t.png"), dpi=140, bbox_inches="tight")

# --- Field diagnostics (the accelerating potential) ----------------------------
# The field series was auto-loaded by run(); plot_fields finds it automatically.
fig = w.plot_fields("phi", "x", "z")
fig.savefig(os.path.join(HERE, "potential_xz.png"), dpi=140, bbox_inches="tight")

plt.close("all")
print("\nDone. Wrote phase_space_z_KE.png, centroid_z_vs_t.png, potential_xz.png to")
print(f"  {HERE}")
