#!/usr/bin/env python
# NOTE: Example code is generated by Claude Opus 4.8
#
# Drive the 1-D Pierce-diode simulation defined in pierce_diode.yaml and make a
# few diagnostic plots of the space-charge-limited ion beam.
#
#   python run.py
#
# Diagnostics are written under <path>/diags; we set path=./output.

import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from warpx import WarpX

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "output")

w = WarpX(input_file=os.path.join(HERE, "pierce_diode.yaml"), path=OUTDIR, verbose=True)
w.run()  # configures, steps the simulation, and auto-loads every diagnostic series

# --- Beam diagnostics (particles) ----------------------------------------------
# Longitudinal phase space: z vs. kinetic energy. The K+ ions accelerate across
# the -93 kV gap and approach ~93 keV at the anode.
fig = w.plot2D("z", "kinetic_energy", species="ions")
fig.savefig(os.path.join(HERE, "phase_space_z_KE.png"), dpi=140, bbox_inches="tight")

# Longitudinal momentum vs. position: the acceleration profile across the gap
# (pz grows monotonically as the ions fall through the -93 kV potential).
fig = w.plot2D("z", "pz", species="ions")
fig.savefig(os.path.join(HERE, "pz_profile_z.png"), dpi=140, bbox_inches="tight")

# Beam population vs. time: continuous injection builds the beam up to the
# steady-state space-charge-limited current.
fig = w.plot1D("t", "n_particle", species="ions")
fig.savefig(os.path.join(HERE, "n_particle_vs_t.png"), dpi=140, bbox_inches="tight")

plt.close("all")
print("\nDone. Wrote phase_space_z_KE.png, pz_profile_z.png, n_particle_vs_t.png to")
print(f"  {HERE}")
